import bpy
import csv
import math
from mathutils import Euler


def import_camera_log(csv_path: str, camera_name: str = "Camera"):
    """Import camera position and orientation from a CSV log.

    The log should be the one generated by the Kh2 Motion Editor and contain the
    following header: Time,X,Y,Z,Yaw,Pitch,Roll
    """
    cam = bpy.data.objects.get(camera_name)
    if cam is None:
        print(f"Camera '{camera_name}' not found")
        return

    frame = bpy.context.scene.frame_start
    with open(csv_path, newline='') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            x = float(row['X'])
            y = float(row['Y'])
            z = float(row['Z'])
            yaw = float(row['Yaw'])
            pitch = float(row['Pitch'])
            roll = float(row['Roll'])

            cam.location = (-x, y, z)
            cam.rotation_euler = Euler(
                (
                    math.radians(pitch),
                    math.radians(yaw),
                    math.radians(roll),
                ),
                'XYZ'
            )
            cam.keyframe_insert(data_path="location", frame=frame)
            cam.keyframe_insert(data_path="rotation_euler", frame=frame)
            frame += 1


# Example usage:
# import_camera_log("/path/to/camera-log.csv")
